twitter:
  username: margostino
  api_key: ${API_KEY}
  api_secret: ${API_SECRET}
  access_key: ${ACCESS_KEY}
  access_secret: ${ACCESS_SECRET}

commands:
  - id: rank creators
    description: "Get friends with latest tweet"
    action: ExecuteRankCreators