twitter:
  username: margostino
  api_key: ${API_KEY}
  api_secret: ${API_SECRET}
  access_key: ${ACCESS_KEY}
  access_secret: ${ACCESS_SECRET}

commands:
  - id: rank users by
    description: "Get friends ranking sorted by field(s)"
    action: ExecuteRankUsersBy
    args: 51
    pattern: "^rank users by (status|age|fav|followers|following)( asc| desc)?$"
  - id: select users where
    description: "Select and filter users by condition(s)"
    action: ExecuteSelectUsersWhere
    args: 51
    pattern: "^select users [a-z-A-Z]+ (like|=|<|>|<>) [a-z-A-Z]+$"
  - id: snapshot users
    description: "Collect and save an updated list of friends"
    action: ExecuteSnapshotUsers
  - id: help
    description: "List available commands"
    action: ExecuteHelp
  - id: exit
    description: "Exit shell"
    action: ExecuteExit