store:
  users: data/users

twitter:
  username: margostino
  api_key: ${API_KEY}
  api_secret: ${API_SECRET}
  access_key: ${ACCESS_KEY}
  access_secret: ${ACCESS_SECRET}

commands:
  - id: rank users by
    description: "Get friends ranking sorted by field(s)"
    action: ExecuteRankUsersBy
    args: 2
    pattern: "^rank users by (status|age|fav|followers|following)( asc| desc)?$"
  - id: select users where
    description: "Select and filter users by condition(s)"
    action: ExecuteSelectUsersWhere
    args: 3
    pattern: "^select users where (description|name|email|status) (like|=|not like) [a-zA-Z0-9_]+$"
  - id: snapshot users
    description: "Collect and save an updated list of friends"
    action: ExecuteSnapshotUsers
  - id: help
    description: "List available commands"
    action: ExecuteHelp
  - id: exit
    description: "Exit shell"
    action: ExecuteExit
  - id: show stats
    description: "Show general stats from user"
    action: ExecuteShowStats

quotes:
  - author: Albert Einstein
    quote: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe."
  - author: Steve Jobs
    quote: "Stay hungry, stay foolish."
  - author: Stephen King
    quote: "The trust of the innocent is the liar's most useful tool."
  - author: J.R.R. Tolkien
    quote: "Not all those who wander are lost."
  - author: J.R.R. Tolkien
    quote: "Faithless is he that says farewell when the road darkens."
  - author: Jorge Luis Borges
    quote: "Being with you and not being with you is the only way I have to measure time."
